viaa:
    logging:
        level: DEBUG
app:
    pulsar:
        host: !ENV ${PULSAR_HOST}
        port: !ENV ${PULSAR_PORT}
        consumer_topic: !ENV ${REGISTRATOR_CONSUMER_TOPIC}
        producer_topic: !ENV ${REGISTRATOR_PRODUCER_TOPIC}

    db:
        host: !ENV ${DB_HOST}
        port: !ENV ${DB_PORT}
        dbname: !ENV ${DB_NAME}
        username: !ENV ${DB_USERNAME}
        password: !ENV ${DB_PASSWORD}
        table: !ENV ${DB_TABLE}